version: '3.8'
services:
  angular-app:
    image: node:14-alpine
    container_name: angular-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    command: npm start
