version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mpm
    ports:
      - "3307:3306"
    networks:
      - my-network

  app:
    image: mpm-api
    ports:
      - "8080:80"
    networks:
      - my-network
    depends_on:
      - mysql
    restart: on-failure

networks:
  my-network:
